In [3]:
import numpy as np
import pandas as pd
import time
import random

Create a two-dimensional NumPy array of size 10x10 with random values between 0
and 1.
a) Add 10 with each element individually using any loop in python
b) Perform vector addition to add 10 with each element.
c) Compare the time taken by the above two operations.

In [2]:
arr = np.random.rand(10,10)

In [6]:
start_time=time.time()
for i in range(10):
    for j in range(10):
        arr[i][j] += 10
time_taken_1=time.time() - start_time;

In [7]:
start_time=time.time()
arr = arr +10 # arr = np.add(arr,10)
time_taken_2= time.time() - start_time

In [8]:
print(f"Time taken for operation 1: {time_taken_1} seconds")
print(f"Time taken for operation 2: {time_taken_2} seconds")

Time taken for operation 1: 0.32830238342285156 seconds
Time taken for operation 2: 0.08845329284667969 seconds


vector addition takes lesser time

2. Create a pandas data frame with columns (roll no, name, subject, age, marks)
a) Add 10 student information into the data frame
b) Find out the minimum, maximum, mean, median, and standard deviation of
the marks obtained by the students.

In [10]:
df = pd.DataFrame(columns=["roll no", "name","subject", "age","marks"])

In [13]:
for i in range(10):
    df.loc[i] = [i+1, "Student" + str(i+1), "Science", 20, i+50]
   

In [18]:
df['marks'].mean()

54.5

In [19]:
df['marks'].max()

59

In [20]:
df['marks'].median()

54.5

In [21]:
df['marks'].std()

3.0276503540974917

Create a function that sums all numbers. It should work for both the inputs: 5,6,7,8,9
as separate args and as a list [5,6,7,8,9]

In [9]:
def sum_numbers(*args):
    if(type(args[0]) == list):
        return sum(args[0])
    else:
        return sum(args)

In [10]:
print(sum_numbers([5,3,4,2]))

14


Check whether two given strings are anagrams or not.
Anagrams example( below = elbow, study = dusty, night = thing)

In [26]:
def anagram(string1,string2):
    return sorted(string1)==sorted(string2)

In [27]:
print(anagram('anant','tnana'))

True


5. i) Create a list L of size 9 of random numbers ranging from 5 to 9.
ii) Count the frequency of each number on that list.
iii) Print the values of indexes of the number which has the highest frequency.

In [4]:
L=[]
for i in range(9):
    L.append(random.randrange(5,9))

In [5]:
from collections import Counter

counts = Counter(L)
print(counts)

Counter({5: 4, 7: 3, 8: 1, 6: 1})


In [39]:
"""counts={}
for num in L:
    if num in counts:
        counts[num] += 1
    else:
        counts[num] = 1"""

'counts={}\nfor num in L:\n    if num in counts:\n        counts[num] += 1\n    else:\n        counts[num] = 1'

In [6]:
most_common = max(counts, key=counts.get)

The enumerate() function in Python takes an iterable object, such as a list, and returns an iterator that produces tuples containing the index and the value of each element of the object. It is commonly used to iterate over a list while keeping track of the index of the current element.

In [7]:
indexes =[i for i, x in enumerate(L) if x==most_common]

In [42]:
print(indexes)

[0, 2, 5, 8]


6. i) Create a list L1 of random numbers (size of 10 or more) ranging from 40 to 49.
ii) Create another list L2 of random numbers (size of 10 or more) ranging from 41 to
48.
iii) Create another list L by selecting the even indexing element from L1 and the odd
indexing element from L2

In [51]:
L1=[]
for i in range(10):
    L1.append(random.randrange(40,49))

In [52]:
L2=[]
for i in range(10):
    L2.append(random.randrange(41,48))

In [53]:
L3=[]
for i in range(10):
    if i%2==0:
        L3.append(L1[i])
    else:
        L3.append(L2[i])

Create a function that takes a list and returns a new list with unique elements of the
first list

In [54]:
def unique_list(L):
    A =[]
    for x in L:
        if x not in A:
            A.append(x)
    return A

In [55]:
print(unique_list([1,2,3,3,3,5,6,3,3,6]))

[1, 2, 3, 5, 6]


Create a random 20 x 5 array and extract the first ten rows of the array and store
them into a variable

In [56]:
arr=np.random.rand(20,5)

In [57]:
first_ten_rows=arr[:10]

In [58]:
print(first_ten_rows)

[[0.70246718 0.23170948 0.71376165 0.81745679 0.67797652]
 [0.4906733  0.11774352 0.53250965 0.92111408 0.73693403]
 [0.87756217 0.18832811 0.16243704 0.98641956 0.87892125]
 [0.23324719 0.87497538 0.99641224 0.57850249 0.98279061]
 [0.54828883 0.08743722 0.90326267 0.28029224 0.41479827]
 [0.02210696 0.97508613 0.13954538 0.12640879 0.74233058]
 [0.57412247 0.60825462 0.65614313 0.08668197 0.83408027]
 [0.68969387 0.89762979 0.73690385 0.96944518 0.78201508]
 [0.7567765  0.65967353 0.47669808 0.92308125 0.98976675]
 [0.74963701 0.94605977 0.05870617 0.14234273 0.78316215]]


Write a Python program to calculate the sum of all positive, and negative integers
present in a given string.
-100#^sdfkj8902w3ir021@swf-20
Output: positive integer= 9046, negative integer= -120

\d is a regular expression pattern that matches any digit (0-9). When preceded by a + sign, it matches one or more consecutive digits.

In [59]:
import re
def positive_negative_sum(str1):
    positive_values = sum(int(n) for n in re.findall('\d+', str1))
    negative_values = sum(int(n) for n in re.findall('-\d+', str1))
    return positive_values, negative_values

In [60]:
str1 = '-100#^sdfkj8902w3ir021@swf-20'

In [61]:
result = positive_negative_sum(str1)
print("Positive values:",result[0])
print("Negative values:",result[1])

Positive values: 9046
Negative values: -120


There is a given array and split it from a specified position, and move the first part of
the array add to the end.
a[ ]= {5, 16, 62, 23, 7, 12, 18, 3, 1}
Output = {7, 12, 18, 3, 1, 5, 16, 62, 23}

In [62]:
a = [5, 16, 62, 23, 7, 12, 18, 3, 1]
split_pos = 4

# Use slicing to split the array
first_part = a[:split_pos]
second_part = a[split_pos:]

# Use concatenation to move the first part to the end
result = second_part + first_part

print(result)


[7, 12, 18, 3, 1, 5, 16, 62, 23]


## Nested Comprehensions

In [63]:
# 2-D List
matrix = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

# Nested List Comprehension to flatten a given 2-D matrix
flatten_matrix = [val for sublist in matrix for val in sublist]

print(flatten_matrix)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
M=4
N=3
def transpose(A, B):
 
 for i in range(N):
    for j in range(M):
        B[i][j] = A[j][i]

12. Given a dictionary in Python, write a Python program to find the sum of all items in the
dictionary.
Input : {‘a’: 100, ‘b’:200, ‘c’:300}
Output: 600

In [67]:
my_dict = {'a': 100, 'b': 200, 'c': 300}

# Use the sum() function and the values() method to find the sum of all items in the dictionary
result = sum(my_dict.values())

print(result)

600
